Adding Connect , Search and new output messages .

diff --git a/sshconfig b/sshconfig
--- a/sshconfig
+++ b/sshconfig
@@ -29,7 +29,21 @@ do_check_names() {
 	grep "^Host" $CONFIGFILE | cut -f2- -d " "
 	exit 0
 }
-	
+
+success() {
+	printf "\n  \033[32mSuccess: %s\033[0m\n\n" "$@"
+	exit 0
+}
+
+error() {
+	printf "\n  \033[31mError: %s\033[0m\n\n" "$@"
+	exit 1
+}
+
+print() {
+	printf "  \033[36m%10s\033[0m : \033[90m%s\033[0m\n" "$1" "$2"
+}
+
 do_add_process() {
     if [[ "$#" -eq 6 || "$#" -eq 4 ]]; then
 	name=$2
@@ -56,13 +70,11 @@ do_add_process() {
 	    port=22
 	fi
     else
-	echo "Usage : ssc $1 NAME USERNAME HOSTNAME [IdentityKey] [PORT]"
-	exit 1
+	error "ssc $1 NAME USERNAME HOSTNAME [IdentityKey] [PORT]"
     fi
 
     if [[ $(do_check_names | grep --count "^$name$") != 0 ]]; then
-	echo "This name is already used. Try again with another name."
-	exit 1
+	error "This name is already used. Try again with another name."
     fi
     
     if [ -n "$id" ]; then
@@ -83,20 +95,20 @@ Host $name
 	Port $port
 EOB
     fi
-    exit 0
+    success "\"$name\" added successfuly to host list"
 }
 
 do_remove_process() {
     if [ "$#" != 2 ]; then
-	echo "Usage : ssc $1 NAME"
-	exit 1
+	error "Usage : ssc $1 NAME"
     fi
     name=$2
     if [[ $(do_check_names | grep --count "^$name$") != 0 ]]; then
 	sed -ie "/^Host $name$/,/^$/d" $CONFIGFILE
+	success "\"$name\" Removed successfully"
     	exit 0
     else
-	echo "Sorry, \"$name\" is not in list"
+	error "Sorry, \"$name\" is not in list"
     fi
 }
 
@@ -104,49 +116,65 @@ do_list_process() {
     if [ -n "$2" ]; then
      	name=$2
 	if [[ $(do_check_names | grep --count "^$name$") != 0 ]]; then
-		awk -v name="$name" -v green="\033[0;32m" -v reset="\033[0m" -v RS='' 'index($0, name) { for (i = 1; i < NF; i += 2) { printf("%s%s%s  %s%s", green, $i, reset, $(i + 1), (i < NF -2)? "  ": "\n") } exit }' $CONFIGFILE
+		awk -v name="$name" -v green="\033[0;32m" -v reset="\033[0m" -v RS='' 'index($0, name) { for (i = 1; i < NF; i += 2) { printf("%s%s%s: %s%s", green, $i, reset, $(i + 1), (i < NF -2)? "  ": "\n") } exit }' $CONFIGFILE
 		exit 0
 	else
-		echo "Sorry, \"$name\" is not in list"
-		exit 1
+		error "Sorry, \"$name\" is not in list"
 	fi
     else
-	 awk -v name="$name" -v green="\033[0;32m" -v reset="\033[0m" -v RS='' '{ for (i = 1; i < NF; i += 2) { printf("%s%s%s  %s%s", green, $i, reset, $(i + 1), (i < NF -2)? "  ": "\n") } }' $CONFIGFILE
+	 awk -v name="$name" -v green="\033[0;32m" -v reset="\033[0m" -v RS='' '{ for (i = 1; i < NF; i += 2) { printf("%s%s%s: %s\t%s", green, $i, reset, $(i + 1), (i < NF -2)? "  ": "\n") } }' $CONFIGFILE
     fi
 }
 
+do_connect() {
+	name=$1
+	if [[ $(do_check_names | grep --count "^$name$") != 0 ]]; then
+		ssh $1
+		exit 0
+	fi
+}
+
+do_search_process() {
+	name=$2
+	ssc ls | grep $name
+}
+
 do_show_usage() {
-	echo -e "Add a new Host: ssc add/-a/a NAME USERNAME HOSTNAME [IdentityKey] [PORT] "
-	echo -e "Remove a Host: ssc remove/-r/r  NAME"
-	echo -e "List all exist hosts: ssc list/ls/show"
-	echo -e "Print Version and info: ssc version/-v/v/-V"
-	echo -e "Print this message and exit: ssc help/-h/h"
+	print "Add" "ssc add/-a NAME USERNAME HOSTNAME [IdentityKey] [PORT] "
+	print "Remove" "ssc remove/-r/rm  NAME"
+	print "List" "ssc list/-l/ls [NAME]"
+	print "Search" "ssc search/-s NAME"
+	print "Version" "ssc version/-v"
+	print "Help" "ssc help/-h"
 }
 
 do_show_version() {
-	echo "Create by Arash Shams <xsysxpert@gmail.com>" 
-	echo "Version 1.6 Stable"
-	echo "Fork me at Github <https://github.com/Ara4Sh/sshconfig>"
+	print "Version" "Version 1.7 Stable"
+	print "Contribute" "Fork me at Github <https://github.com/Ara4Sh/sshconfig>"
 }
 
 action=$1
 case $action in
-	add | -a | a)
+	add | -a)
 	    do_add_process $@
 	    ;;
-	remove | -r | r)
+	remove | -r | rm)
 	    do_remove_process $@
 	    ;;
-	list | ls | show)
+	list | -l | ls)
 	    do_list_process $@
 	    ;;
-	version | -v | v | -V)
-	    do_show_version $@
+	search | -s)
+	    do_search_process $@
 	    ;;
-	help | -h | h)
-	    do_show_usage $@
+	version | -v)
+	    do_show_version
+	    ;;
+	help | -h)
+	    do_show_usage
 	    ;;
 	*)
+	    do_connect $@
 	    do_show_usage
 	    echo ""
 	    do_show_version
